name = "yearn-prices"
main = ".open-next/worker.js"
compatibility_date = "2026-03-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability.logs]
enabled = true
