name: Deploy Worker

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: yearn/yearn-gha/.github/workflows/cloudflare-deploy.yml@ba1d1e2800e9a0dfd9d47257dc458fbbd4ea6208
    with:
      identity-id: ${{ vars.DOPPLER_PRODUCTION_IDENTITY_ID }}
