name: Warmup Prices

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  warmup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run warmup
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RPC_URL_1: ${{ secrets.RPC_URL_1 }}
          RPC_URL_10: ${{ secrets.RPC_URL_10 }}
          RPC_URL_100: ${{ secrets.RPC_URL_100 }}
          RPC_URL_137: ${{ secrets.RPC_URL_137 }}
          RPC_URL_146: ${{ secrets.RPC_URL_146 }}
          RPC_URL_250: ${{ secrets.RPC_URL_250 }}
          RPC_URL_8453: ${{ secrets.RPC_URL_8453 }}
          RPC_URL_42161: ${{ secrets.RPC_URL_42161 }}
          RPC_URL_80094: ${{ secrets.RPC_URL_80094 }}
          RPC_URL_747474: ${{ secrets.RPC_URL_747474 }}
